### ISSUE TITLE
Is leaflet version possible?

### ISSUE THREAD

**Issue by answerquest** [osm-in/openstreetmap.in#1]
Is it possible to load this tilelayer in a leaflet.js map? If so, please share the code!

**Comment by answerquest** [comment]
wow this was long ago. Figured it out!  
Page: https://answerquest.github.io/osm-in.html 
Code: https://github.com/answerquest/answerquest.github.io/blob/master/osm-in.html

**Comment by planemad** [comment]
@answerquest one issue though that those mapbox raster tiles should not be used since they are no longer updated from osm. Same reason i'm switching the homepage to vector tiles.

One option is to use the default mapnik osm tiles, but add some extra boundary geometries on top that give the illusion of a different border. A sort of GL example for this: https://jsfiddle.net/Lcvp5p7x/

**Comment by answerquest** [comment]
@planemad I wouldn't be able to get into vector tiles and all at this point. If the additional boundaries can be rendered as png tiles (with transparency) then it can be combined on top of the bg layer easily.
