### ISSUE TITLE
About using the Api Key in High Volume Websites

### ISSUE THREAD

**Issue by darielnoel** [osm-in/openstreetmap.in#32]
Hi,

Our team created a [map to track the coronavirus spread](https://coronavirus.woxo.tech/) using Openstreet map, however, users complain it does not have the India borders updated. The site is having about 4 million visits per day. 

- What do you recommend us in this scenario? 
- Can we use this Map and the API key available in this repository?

Best, Dariel

**Comment by srikanthlogic** [comment]
@planemad @geohacker ^

**Comment by geohacker** [comment]
@darielnoel I don't maintain this API key and I think it's likely with @planemad, and he'd be the best person to comment.

4 million visit is a lot (🎉) but perhaps you can get around the number of map tiles consumed by setting a max zoom limit because the data is only visualised at a country level? So you can set max zoom to say 4 or 5 and that means people won't fetch too many tiles.

**Comment by planemad** [comment]
Its possible for anyone to use the tiles with their own Mapbox api key https://github.com/osm-in/openstreetmap.in/issues/40
