### ISSUE TITLE
OSM India raster tiles URL doesn't work anymore

### ISSUE THREAD

**Issue by Aravindz** [osm-in/openstreetmap.in#40]
GET request to the URL fails.

**Comment by planemad** [comment]
@Aravindz which url are you referring to? https://openstreetmap.in/ works fine.

**Comment by Aravindz** [comment]
This url

https://{a,b,c}.tiles.mapbox.com/v4/openstreetmap.1b68f018/z/x/y.png?access_token=pk.eyJ1Ijoib3NtLWluIiwiYSI6ImNqcnVxMTNrNTJwbHc0M250anUyOW81MjgifQ.cZnvZEyWT5AzNeO3ajg5tg

This url was working until yesterday. But now this is not working. Can you please resolve it asap??

**Comment by planemad** [comment]
Unfortunately those tiles are no longer available due to a deprecation of a [legacy Mapbox API which was used](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/?/=blog&utm_source=mapbox-blog&utm_campaign=blog%7Cmapbox-blog%7Cdoc-migrate-static%7Cdeprecating-studio-classic-styles-d8892ac38cb4-20-03&utm_term=doc-migrate-static&utm_content=deprecating-studio-classic-styles-d8892ac38cb4).

As a quick fix see if this works if you are using leaflet:

```
var map = L.map('map');
 
L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
attribution: '© <a href="https://www.mapbox.com/about/maps/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>',
tileSize: 512,
maxZoom: 18,
zoomOffset: -1,
id: 'planemad/ckf4xcet7231819mm2e8njlca',
accessToken: 'pk.YOUR_MAPBOX_ACCESS_TOKEN'
}).addTo(map);
```

Get a free token from mapbox.com which should be sufficient for upto 50,000 tiles/month. Will try to document this in the repo so others can use it.
